### ISSUE TITLE
Why is MadZ a little girl?

### ISSUE THREAD

**Issue by rederpz** [DarkStorm652/Minecraft-GUI-API#1]
MadZ is a little girl do you have any way to change this? It is starting to scare me.

See this one here? https://hackforums.net/member.php?action=profile&uid=2213063

**Comment by Marioooo** [comment]
Got the same problem :S
Pls, help.

**Comment by masl123** [comment]
You have to Create a Tick Event Listener and call the Update Method of your GuiManager.

**Comment by iQuintennn** [comment]
@masl123 More information???

**Comment by DarkStorm652** [comment]
@iQuintennn call the update method of your GuiManager every tick.

**Comment by OrangeMan432** [comment]
well that was an interesting read...
<br>
<br>
<br>
###### I may do this on another repo sometime...
